/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_api_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Instrument */
        put: operations["update_instrument_api_instruments__instrument_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Holdings */
        get: operations["list_holdings_api_holdings_get"];
        put?: never;
        /** Create Holding */
        post: operations["create_holding_api_holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{holding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Holding */
        put: operations["update_holding_api_holdings__holding_id__put"];
        post?: never;
        /** Delete Holding */
        delete: operations["delete_holding_api_holdings__holding_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Summary */
        get: operations["portfolio_summary_api_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Prices */
        post: operations["refresh_prices_api_prices_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Price */
        get: operations["get_price_api_prices__instrument_id__get"];
        /** Set Manual Price */
        put: operations["set_manual_price_api_prices__instrument_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/montecarlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Montecarlo */
        post: operations["montecarlo_api_simulation_montecarlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "etf" | "stock" | "bond" | "cash" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldingCreate */
        HoldingCreate: {
            instrument: components["schemas"]["InstrumentInput"];
            /** Quantity */
            quantity: number;
            /** Avg Cost Price */
            avg_cost_price: number;
            /** Cost Currency */
            cost_currency: string;
        };
        /** HoldingOut */
        HoldingOut: {
            /** Id */
            id: number;
            instrument: components["schemas"]["InstrumentOut"];
            /** Quantity */
            quantity: number;
            /** Avg Cost Price */
            avg_cost_price: number;
            /** Cost Currency */
            cost_currency: string;
        };
        /** HoldingUpdate */
        HoldingUpdate: {
            /** Quantity */
            quantity?: number | null;
            /** Avg Cost Price */
            avg_cost_price?: number | null;
            /** Cost Currency */
            cost_currency?: string | null;
        };
        /**
         * InstrumentInput
         * @description Either point at an existing instrument by id, or describe a new
         *     one to create inline — matches the "crea Instrument inline se serve"
         *     requirement for holding creation. Matching for de-dup happens in
         *     holdings_service (by isin, then ticker) so re-adding the same
         *     instrument reuses the existing row instead of duplicating it.
         */
        InstrumentInput: {
            /** Instrument Id */
            instrument_id?: number | null;
            /** Isin */
            isin?: string | null;
            /** Ticker */
            ticker?: string | null;
            /** Name */
            name?: string | null;
            /** Currency */
            currency?: string | null;
            /** @default etf */
            asset_class: components["schemas"]["AssetClass"];
            /**
             * Auto Price Enabled
             * @default true
             */
            auto_price_enabled: boolean;
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Id */
            id: number;
            /** Isin */
            isin: string | null;
            /** Ticker */
            ticker: string | null;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            asset_class: components["schemas"]["AssetClass"];
            /** Auto Price Enabled */
            auto_price_enabled: boolean;
        };
        /** InstrumentUpdate */
        InstrumentUpdate: {
            /** Name */
            name: string;
        };
        /** ManualPriceIn */
        ManualPriceIn: {
            /** Price */
            price: number;
            /** Currency */
            currency: string;
        };
        /** MonteCarloRequest */
        MonteCarloRequest: {
            /** Seed Capital */
            seed_capital: number;
            /** Monthly Contribution */
            monthly_contribution: number;
            /** Years */
            years: number;
            /** Expected Annual Return */
            expected_annual_return: number;
            /** Annual Volatility */
            annual_volatility: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Random Seed */
            random_seed?: number | null;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /** Months */
            months: number[];
            /** P5 */
            p5: number[];
            /** P25 */
            p25: number[];
            /** P50 */
            p50: number[];
            /** P75 */
            p75: number[];
            /** P95 */
            p95: number[];
            /** Final Mean */
            final_mean: number;
            /** Final Median */
            final_median: number;
            /** Final P5 */
            final_p5: number;
            /** Final P95 */
            final_p95: number;
        };
        /** PortfolioSummaryOut */
        PortfolioSummaryOut: {
            /** Base Currency */
            base_currency: string;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Total Value Base */
            total_value_base: number;
            /** Total Cost Base */
            total_cost_base: number;
            /** Total Pnl Base */
            total_pnl_base: number;
            /** Currency Exposure */
            currency_exposure: {
                [key: string]: number;
            };
        };
        /** PositionOut */
        PositionOut: {
            /** Instrument Id */
            instrument_id: number;
            /** Instrument Name */
            instrument_name: string;
            /** Quantity */
            quantity: number;
            /** Price Currency */
            price_currency: string;
            /** Price Status */
            price_status: string;
            /** Value Base */
            value_base: number | null;
            /** Cost Base */
            cost_base: number | null;
            /** Pnl Base */
            pnl_base: number | null;
            /** Exclusion Reason */
            exclusion_reason: string | null;
        };
        /** PriceOut */
        PriceOut: {
            /** Instrument Id */
            instrument_id: number;
            /** Price */
            price: number;
            /** Currency */
            currency: string;
            source: components["schemas"]["PriceSource"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
        };
        /**
         * PriceSource
         * @enum {string}
         */
        PriceSource: "yfinance" | "manual";
        /**
         * PriceStatus
         * @enum {string}
         */
        PriceStatus: "ok" | "manual" | "missing";
        /** PriceStatusOut */
        PriceStatusOut: {
            /** Instrument Id */
            instrument_id: number;
            status: components["schemas"]["PriceStatus"];
            /** Price */
            price?: number | null;
            /** Currency */
            currency?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_instruments_api_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
        };
    };
    update_instrument_api_instruments__instrument_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_holdings_api_holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"][];
                };
            };
        };
    };
    create_holding_api_holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_holding_api_holdings__holding_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holding_api_holdings__holding_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_summary_api_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummaryOut"];
                };
            };
        };
    };
    refresh_prices_api_prices_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceStatusOut"][];
                };
            };
        };
    };
    get_price_api_prices__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_manual_price_api_prices__instrument_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPriceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    montecarlo_api_simulation_montecarlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
