/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Instruments
         * @description Every instrument the import has ever seen, included or not.
         */
        get: operations["list_instruments_api_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Instrument */
        put: operations["update_instrument_api_instruments__instrument_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions
         * @description Positions derived from the transaction ledger, for the instruments
         *     the user has included.
         */
        get: operations["list_positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Summary */
        get: operations["portfolio_summary_api_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio History
         * @description Full available daily history per held instrument + the aggregate
         *     portfolio value series. Fetched from the price provider on each call
         *     (yfinance period=max); the frontend caches it and does horizon
         *     slicing / smoothing client-side, so switching views hits no network.
         */
        get: operations["portfolio_history_api_portfolio_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Prices */
        post: operations["refresh_prices_api_prices_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Price */
        get: operations["get_price_api_prices__instrument_id__get"];
        /** Set Manual Price */
        put: operations["set_manual_price_api_prices__instrument_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/montecarlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Montecarlo */
        post: operations["montecarlo_api_simulation_montecarlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Transactions
         * @description Import a Fineco 'Movimenti Dossier Titoli' xlsx. Only operations
         *     for instruments already in the portfolio are stored; re-importing an
         *     overlapping export is idempotent (dedup by natural key).
         */
        post: operations["import_transactions_api_transactions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/composition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Composition
         * @description Value-weighted geographic + sector exposure of the portfolio, from
         *     stored look-through breakdowns.
         */
        get: operations["get_composition_api_composition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/composition/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Composition
         * @description Fetch geo/sector breakdowns for every held instrument from the
         *     composition provider (JustETF) and store them.
         */
        post: operations["refresh_composition_api_composition_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "etf" | "stock" | "bond" | "cash" | "other";
        /** Body_import_transactions_api_transactions_import_post */
        Body_import_transactions_api_transactions_import_post: {
            /** File */
            file: string;
        };
        /** CompositionOut */
        CompositionOut: {
            /** Dimensions */
            dimensions: {
                [key: string]: components["schemas"]["WeightSliceOut"][];
            };
            /** Coverage */
            coverage: {
                [key: string]: number;
            };
            /** Missing */
            missing: {
                [key: string]: string[];
            };
            /** Instruments */
            instruments: components["schemas"]["InstrumentCompositionOut"][];
        };
        /** CompositionRefreshOut */
        CompositionRefreshOut: {
            /** Updated */
            updated: string[];
            /** Failed */
            failed: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryPointOut */
        HistoryPointOut: {
            /** Date */
            date: string;
            /** Close */
            close: number;
        };
        /** ImportResultOut */
        ImportResultOut: {
            /** Imported */
            imported: number;
            /** Duplicates */
            duplicates: number;
            /** Created Instruments */
            created_instruments: string[];
        };
        /** InstrumentCompositionOut */
        InstrumentCompositionOut: {
            /** Instrument Id */
            instrument_id: number;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string | null;
            /** Dimensions */
            dimensions: {
                [key: string]: components["schemas"]["WeightSliceOut"][];
            };
        };
        /** InstrumentHistoryOut */
        InstrumentHistoryOut: {
            /** Instrument Id */
            instrument_id: number;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string | null;
            /** Currency */
            currency: string;
            /** Points */
            points: components["schemas"]["HistoryPointOut"][];
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Id */
            id: number;
            /** Isin */
            isin: string | null;
            /** Ticker */
            ticker: string | null;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            asset_class: components["schemas"]["AssetClass"];
            /** Auto Price Enabled */
            auto_price_enabled: boolean;
            /** Included */
            included: boolean;
        };
        /**
         * InstrumentPositionOut
         * @description An instrument plus the position derived from its transactions.
         */
        InstrumentPositionOut: {
            instrument: components["schemas"]["InstrumentOut"];
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
            /** Invested */
            invested: number;
            /** Commissions */
            commissions: number;
            /** Transaction Count */
            transaction_count: number;
        };
        /**
         * InstrumentUpdate
         * @description Every field optional: the UI patches one thing at a time (rename,
         *     set a ticker, include/exclude).
         */
        InstrumentUpdate: {
            /** Name */
            name?: string | null;
            /** Ticker */
            ticker?: string | null;
            /** Included */
            included?: boolean | null;
        };
        /** ManualPriceIn */
        ManualPriceIn: {
            /** Price */
            price: number;
            /** Currency */
            currency: string;
        };
        /** MonteCarloRequest */
        MonteCarloRequest: {
            /** Seed Capital */
            seed_capital: number;
            /** Monthly Contribution */
            monthly_contribution: number;
            /** Years */
            years: number;
            /** Expected Annual Return */
            expected_annual_return: number;
            /** Annual Volatility */
            annual_volatility: number;
            /**
             * N Paths
             * @default 10000
             */
            n_paths: number;
            /** Random Seed */
            random_seed?: number | null;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /** Months */
            months: number[];
            /** P5 */
            p5: number[];
            /** P25 */
            p25: number[];
            /** P50 */
            p50: number[];
            /** P75 */
            p75: number[];
            /** P95 */
            p95: number[];
            /** Final Mean */
            final_mean: number;
            /** Final Median */
            final_median: number;
            /** Final P5 */
            final_p5: number;
            /** Final P95 */
            final_p95: number;
        };
        /** PortfolioHistoryOut */
        PortfolioHistoryOut: {
            /** Base Currency */
            base_currency: string;
            /** Series */
            series: components["schemas"]["InstrumentHistoryOut"][];
            /** Portfolio */
            portfolio: components["schemas"]["PortfolioValuePointOut"][];
            /** Warnings */
            warnings: string[];
        };
        /** PortfolioSummaryOut */
        PortfolioSummaryOut: {
            /** Base Currency */
            base_currency: string;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Total Value Base */
            total_value_base: number;
            /** Total Cost Base */
            total_cost_base: number;
            /** Total Pnl Base */
            total_pnl_base: number;
            /** Currency Exposure */
            currency_exposure: {
                [key: string]: number;
            };
            /** Xirr */
            xirr: number | null;
        };
        /** PortfolioValuePointOut */
        PortfolioValuePointOut: {
            /** Date */
            date: string;
            /** Value */
            value: number;
            /** Invested */
            invested: number;
        };
        /** PositionOut */
        PositionOut: {
            /** Instrument Id */
            instrument_id: number;
            /** Instrument Name */
            instrument_name: string;
            /** Quantity */
            quantity: number;
            /** Price Currency */
            price_currency: string;
            /** Price Status */
            price_status: string;
            /** Value Base */
            value_base: number | null;
            /** Cost Base */
            cost_base: number | null;
            /** Pnl Base */
            pnl_base: number | null;
            /** Exclusion Reason */
            exclusion_reason: string | null;
            /** Avg Cost Source */
            avg_cost_source: string;
            /** Xirr */
            xirr: number | null;
        };
        /** PriceOut */
        PriceOut: {
            /** Instrument Id */
            instrument_id: number;
            /** Price */
            price: number;
            /** Currency */
            currency: string;
            source: components["schemas"]["PriceSource"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
        };
        /**
         * PriceSource
         * @enum {string}
         */
        PriceSource: "yfinance" | "manual";
        /**
         * PriceStatus
         * @enum {string}
         */
        PriceStatus: "ok" | "manual" | "missing";
        /** PriceStatusOut */
        PriceStatusOut: {
            /** Instrument Id */
            instrument_id: number;
            status: components["schemas"]["PriceStatus"];
            /** Price */
            price?: number | null;
            /** Currency */
            currency?: string | null;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Id */
            id: number;
            /** Instrument Id */
            instrument_id: number;
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Value Date */
            value_date: string | null;
            sign: components["schemas"]["TransactionSign"];
            /** Quantity */
            quantity: number;
            /** Currency */
            currency: string;
            /** Price */
            price: number;
            /** Fx Rate */
            fx_rate: number;
            /** Gross Amount */
            gross_amount: number;
            /** Commissions */
            commissions: number;
        };
        /**
         * TransactionSign
         * @enum {string}
         */
        TransactionSign: "A" | "V";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightSliceOut */
        WeightSliceOut: {
            /** Key */
            key: string;
            /** Weight */
            weight: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_instruments_api_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
        };
    };
    update_instrument_api_instruments__instrument_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentPositionOut"][];
                };
            };
        };
    };
    portfolio_summary_api_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummaryOut"];
                };
            };
        };
    };
    portfolio_history_api_portfolio_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryOut"];
                };
            };
        };
    };
    refresh_prices_api_prices_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceStatusOut"][];
                };
            };
        };
    };
    get_price_api_prices__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_manual_price_api_prices__instrument_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPriceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    montecarlo_api_simulation_montecarlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
        };
    };
    import_transactions_api_transactions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_transactions_api_transactions_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_composition_api_composition_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompositionOut"];
                };
            };
        };
    };
    refresh_composition_api_composition_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompositionRefreshOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
