"""instruments carry included flag; drop manual holding table

Revision ID: 365c5c7caee4
Revises: ea6debac085e
Create Date: 2026-07-25 13:07:38.497658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '365c5c7caee4'
down_revision: Union[str, Sequence[str], None] = 'ea6debac085e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required: without it, adding a NOT NULL column to
    # a table that already has rows fails. Existing instruments were all
    # deliberately added, so they default to included.
    op.add_column(
        'instrument',
        sa.Column('included', sa.Boolean(), nullable=False, server_default=sa.true()),
    )

    # Positions now come from the transaction ledger, so the hand-entered
    # holding rows are redundant (their quantities are reproduced exactly
    # by replaying the imported buys and sells).
    op.drop_index(op.f('ix_holding_instrument_id'), table_name='holding')
    op.drop_table('holding')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument', 'included')
    op.create_table('holding',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('avg_cost_price', sa.FLOAT(), nullable=False),
    sa.Column('cost_currency', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_instrument_id'), 'holding', ['instrument_id'], unique=False)
    # ### end Alembic commands ###
