"""initial schema

Revision ID: 78fe3094cec4
Revises: 
Create Date: 2026-07-20 22:43:36.898571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78fe3094cec4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_class', sa.Enum('etf', 'stock', 'bond', 'cash', 'other', name='assetclass'), nullable=False),
    sa.Column('auto_price_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_isin'), 'instrument', ['isin'], unique=True)
    op.create_index(op.f('ix_instrument_ticker'), 'instrument', ['ticker'], unique=True)
    op.create_table('compositionbreakdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Enum('geography', 'sector', name='breakdowndimension'), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'csv', 'api', name='breakdownsource'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compositionbreakdown_instrument_id'), 'compositionbreakdown', ['instrument_id'], unique=False)
    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost_price', sa.Float(), nullable=False),
    sa.Column('cost_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_instrument_id'), 'holding', ['instrument_id'], unique=False)
    op.create_table('pricesnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.Enum('yfinance', 'manual', name='pricesource'), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricesnapshot_as_of'), 'pricesnapshot', ['as_of'], unique=False)
    op.create_index(op.f('ix_pricesnapshot_instrument_id'), 'pricesnapshot', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricesnapshot_instrument_id'), table_name='pricesnapshot')
    op.drop_index(op.f('ix_pricesnapshot_as_of'), table_name='pricesnapshot')
    op.drop_table('pricesnapshot')
    op.drop_index(op.f('ix_holding_instrument_id'), table_name='holding')
    op.drop_table('holding')
    op.drop_index(op.f('ix_compositionbreakdown_instrument_id'), table_name='compositionbreakdown')
    op.drop_table('compositionbreakdown')
    op.drop_index(op.f('ix_instrument_ticker'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_isin'), table_name='instrument')
    op.drop_table('instrument')
    # ### end Alembic commands ###
