"""add transaction table

Revision ID: ea6debac085e
Revises: 78fe3094cec4
Create Date: 2026-07-21 23:16:08.419896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea6debac085e'
down_revision: Union[str, Sequence[str], None] = '78fe3094cec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('sign', sa.Enum('buy', 'sell', name='transactionsign'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fx_rate', sa.Float(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('commissions', sa.Float(), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_dedup_key'), 'transaction', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_transaction_instrument_id'), 'transaction', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_transaction_isin'), 'transaction', ['isin'], unique=False)
    op.create_index(op.f('ix_transaction_trade_date'), 'transaction', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_trade_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_isin'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_instrument_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_dedup_key'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
